[build]
publish = "dist"  # Répertoire où se trouve la sortie du build
command = "npm run build"  # Commande pour construire votre projet

# Contextes de déploiement optionnels
[context.production.environment]
  NODE_ENV = "production"
